version: 2.1

jobs:
  sync:
    docker:
      - image: cimg/openjdk:11.0
    environment:
      COPYBARA_TAG: v20250818
    steps:
      - checkout

      - run:
          name: Instalar herramientas básicas
          command: |
            sudo apt-get update -y
            sudo apt-get install -y curl git openssh-client

      - run:
          name: Instalar Bazelisk
          command: |
            curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o bazelisk
            chmod +x bazelisk
            sudo mv bazelisk /usr/local/bin/bazel
            bazel --version

      # ---- CACHE: código fuente de Copybara (clonado) ----
      - restore_cache:
          keys:
            - v1-copybara-src-{{ .Environment.COPYBARA_TAG }}
      - run:
          name: Clonar Copybara (si no está en caché)
          command: |
            if [ ! -d copybara ]; then
              git clone https://github.com/google/copybara.git
              cd copybara
              git checkout "${COPYBARA_TAG}" || git checkout master
            else
              echo "Usando Copybara desde caché"
              cd copybara
              # Asegura que estamos en el tag correcto; si falla, usamos master
              git checkout "${COPYBARA_TAG}" || git checkout master
            fi
      - save_cache:
          key: v1-copybara-src-{{ .Environment.COPYBARA_TAG }}
          paths:
            - copybara

      # ---- CACHE: Bazel (solo repos externos y opcional disk cache) ----
      - run: mkdir -p ~/.bazel_repo_cache ~/.bazel_disk_cache
      - restore_cache:
          keys:
            - v3-bazel-repo-{{ checksum "copybara/.bazelversion" }}-{{ .Environment.COPYBARA_TAG }}
            - v3-bazel-repo-
      - restore_cache:
          keys:
            - v1-bazel-disk-{{ checksum "copybara/.bazelversion" }}-{{ .Environment.COPYBARA_TAG }}
            - v1-bazel-disk-

      - run:
          name: Compilar Copybara
          command: |
            cd copybara
            bazelisk shutdown || true
            rm -rf ~/.cache/bazel/_bazel_${USER}/install || true
            bazel build \
              --repository_cache=$HOME/.bazel_repo_cache \
              --disk_cache=$HOME/.bazel_disk_cache \
              //java/com/google/copybara

      - save_cache:
          key: v3-bazel-repo-{{ checksum "copybara/.bazelversion" }}-{{ .Environment.COPYBARA_TAG }}
          paths:
            - ~/.bazel_repo_cache
      - save_cache:
          key: v1-bazel-disk-{{ checksum "copybara/.bazelversion" }}-{{ .Environment.COPYBARA_TAG }}
          paths:
            - ~/.bazel_disk_cache

      - run:
          name: Configurar identidad de Git
          command: |
            git config --global user.name "Julimax"
            git config --global user.email "julimax951@gmail.com"

      - run:
          name: Configurar SSH
          command: |
            mkdir -p ~/.ssh
            echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_ed25519

      - run:
          name: Ejecutar Copybara
          command: |
            cd copybara
            ./bazel-bin/java/com/google/copybara/copybara ../copy.bara.sky sync_to_dest --force

workflows:
  sync:
    jobs:
      - sync
