version: 2.1

parameters:
  copybara_tag:
    type: string
    default: "v20250818"

jobs:
  check-connection:
    machine: true
    resource_class: org-test-copybara/test
    environment:
      CONTAINER_IMAGE: "copybara-simple:latest" # imagen con Copybara pre-compilado
      COPYBARA_TAG: << pipeline.parameters.copybara_tag >>
    steps:
      - checkout
      - run:
          name: Check env vars
          command: |
            echo "=== Environment Variables Debug ==="
            echo "GH_PAT is set: $([ -n "$GH_PAT" ] && echo 'YES' || echo 'NO')"
            echo "COPYBARA_TAG: $COPYBARA_TAG"
      - run:
          name: Docker diagnostics and setup
          command: |
            echo "=== Docker Diagnostics ==="
            echo "Current user: $(whoami)"
            echo "User groups: $(groups)"
            echo "Docker socket: $(ls -la /var/run/docker.sock 2>/dev/null || echo 'Not found')"
            echo "Docker service status: $(systemctl is-active docker 2>/dev/null || echo 'Unknown')"
            echo "Testing Docker access..."
            if docker version >/dev/null 2>&1; then
              echo "✅ Docker access successful"
            else
              echo "❌ Docker access failed"
              echo "Attempting to fix permissions..."
              # Try to add user to docker group (if not already)
              if ! groups | grep -q docker; then
                echo "User not in docker group. This needs to be fixed on the runner."
              fi
              # Check if we can modify socket permissions
              if [ -w /var/run/docker.sock ]; then
                echo "Socket is writable, continuing..."
              else
                echo "Socket is not writable. Checking if we can fix it..."
                chmod 666 /var/run/docker.sock 2>/dev/null && echo "Fixed socket permissions" || echo "Cannot fix socket permissions"
              fi
            fi
      - run:
          name: Check GitHub Cloud (in-container)
          command: |
            docker run --rm \
              -e GH_PAT -e COPYBARA_TAG \
              -v "$PWD":/workspace -w /workspace \
              "$CONTAINER_IMAGE" bash -lc '
                set -euo pipefail
                URL="https://api.github.com/repos/julimax/copybara2"
                code=$(curl -sS -D /tmp/h -o /tmp/b -w "%{http_code}" \
                  -H "Authorization: Bearer ${GH_PAT}" \
                  -H "Accept: application/vnd.github+json" "$URL")
                echo "== Headers =="; cat /tmp/h
                echo "== Body =="; (jq . /tmp/b || cat /tmp/b)
                echo "HTTP $code"
                test "${code:0:1}" = "2"
              ' 
      - run:
          name: Check GitHub Enterprise (in-container)
          command: |
            docker run --rm \
              -e GH_PAT -e COPYBARA_TAG \
              -v "$PWD":/workspace -w /workspace \
              "$CONTAINER_IMAGE" bash -lc '
                set -euo pipefail
                URL="https://api.github.com/repos/julimax/copybara2"
                code=$(curl -sS --connect-timeout 5 --max-time 15 --retry 3 --retry-delay 2 --retry-all-errors \
                  -D /tmp/h -o /tmp/b -w "%{http_code}" \
                  -H "Authorization: Bearer ${GH_PAT}" \
                  -H "Accept: application/vnd.github+json" "$URL")
                echo "== Headers =="; cat /tmp/h
                echo "== Body =="; (jq . /tmp/b || cat /tmp/b)
                echo "HTTP $code"
                test "${code:0:1}" = "2"
              '

  sync:
    machine: true
    resource_class: org-test-copybara/test
    environment:
      CONTAINER_IMAGE: "copybara-simple:latest" # imagen con Copybara pre-compilado
      COPYBARA_TAG: << pipeline.parameters.copybara_tag >>
    steps:
      - checkout
      - run:
          name: Docker diagnostics and setup
          command: |
            echo "=== Docker Diagnostics ==="
            echo "Current user: $(whoami)"
            echo "User groups: $(groups)"
            echo "Docker socket: $(ls -la /var/run/docker.sock 2>/dev/null || echo 'Not found')"
            echo "Docker service status: $(systemctl is-active docker 2>/dev/null || echo 'Unknown')"
            echo "Testing Docker access..."
            if docker version >/dev/null 2>&1; then
              echo "✅ Docker access successful"
            else
              echo "❌ Docker access failed"
              echo "Attempting to fix permissions..."
              # Try to add user to docker group (if not already)
              if ! groups | grep -q docker; then
                echo "User not in docker group. This needs to be fixed on the runner."
              fi
              # Check if we can modify socket permissions
              if [ -w /var/run/docker.sock ]; then
                echo "Socket is writable, continuing..."
              else
                echo "Socket is not writable. Checking if we can fix it..."
                chmod 666 /var/run/docker.sock 2>/dev/null && echo "Fixed socket permissions" || echo "Cannot fix socket permissions"
              fi
            fi
      - run:
          name: Run Copybara (in-container)
          command: |
            docker run --rm \
              -e GH_PAT="${GH_PAT}" \
              -v "$PWD":/workspace -w /workspace \
              -v ~/.ssh:/tmp/host_ssh:ro \
              -v ~/.gitconfig:/home/circleci/.gitconfig:ro \
              "$CONTAINER_IMAGE" bash -lc '
                set -euo pipefail
                # Configurar SSH y Git para GitHub (copia a directorio escribible)
                mkdir -p /home/circleci/.ssh
                cp -r /tmp/host_ssh/* /home/circleci/.ssh/ 2>/dev/null || true
                chmod 700 /home/circleci/.ssh
                chmod 600 /home/circleci/.ssh/id_* 2>/dev/null || true
                # Agregar GitHub a known_hosts
                ssh-keyscan github.com >> /home/circleci/.ssh/known_hosts 2>/dev/null || echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=" > /home/circleci/.ssh/known_hosts
                # Copybara ya está pre-compilado en la imagen (JAR deploy)
                copybara .circleci/copybara/copy.bara.sky sync_to_dest
              '

workflows:
  build-workflow:
    jobs:
      - check-connection
      - sync:
          requires:
            - check-connection