# Repo B — .circleci/config.yml
version: 2.1

parameters:
  message:
    type: string
    default: "Hello World"

jobs:
  print:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Who triggered me?
          command: |
            sudo apt-get update -y && sudo apt-get install -y jq
            curl -sS -H "Circle-Token: ${CIRCLE_TOKEN}" \
              "https://circleci.com/api/v2/pipeline/${CIRCLE_PIPELINE_ID}" \
            | jq -r '"actor=\(.trigger.actor.login) type=\(.trigger.type) created_at=\(.created_at)"'
      - run:
          name: Print message
          command: echo "<< pipeline.parameters.message >>"

workflows:
  example:
    jobs:
      - print
