version: 2.1

parameters:
  mensaje:
    type: string
    default: "Hola Mundo"

jobs:
  imprimir:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Imprimir mensaje
          command: echo "<< pipeline.parameters.mensaje >>"

workflows:
  ejemplo:
    jobs:
      - imprimir
