name: Sync with Copybara
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (con el copy.bara.sky)
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Setup Bazel (Bazelisk)
        uses: bazelbuild/setup-bazelisk@v3

      - name: Clone Copybara versión v20250818
        run: |
          git clone https://github.com/google/copybara.git
          cd copybara
          git checkout v20250818

      # === Prepara directorios de cache ===
      - name: Prepare caches
        run: |
          mkdir -p "$HOME/.cache/bazel-disk"
          mkdir -p "$HOME/.cache/bazel-repo"
          mkdir -p "$HOME/.cache/bazelisk"

      # === Cache Bazel DISK (resultados de build) ===
      - name: Cache Bazel (disk cache)
        uses: actions/cache@v4
        with:
          path: $HOME/.cache/bazel-disk
          key: bazel-disk-${{ runner.os }}-copybara-v20250818
          restore-keys: |
            bazel-disk-${{ runner.os }}-

      # === Cache Bazel REPOSITORY (descargas externas) ===
      - name: Cache Bazel (repository cache)
        uses: actions/cache@v4
        with:
          path: $HOME/.cache/bazel-repo
          key: bazel-repo-${{ runner.os }}-copybara-v20250818
          restore-keys: |
            bazel-repo-${{ runner.os }}-

      # === Cache BAZELISK (descarga de binarios de bazel) ===
      - name: Cache Bazelisk
        uses: actions/cache@v4
        with:
          path: $HOME/.cache/bazelisk
          key: bazelisk-${{ runner.os }}-1.x
          restore-keys: |
            bazelisk-${{ runner.os }}-

      - name: Build Copybara (usando caches)
        run: |
          cd copybara
          bazel build \
            --disk_cache="$HOME/.cache/bazel-disk" \
            --repository_cache="$HOME/.cache/bazel-repo" \
            //java/com/google/copybara

      - name: Set Git identity
        run: |
          git config --global user.name "Julimax"
          git config --global user.email "julimax951@gmail.com"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: Run Copybara
        run: |
          cd copybara
          ./bazel-bin/java/com/google/copybara/copybara ../copy.bara.sky sync_to_dest
