
name: Sync with Copybara

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (con el copy.bara.sky)
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Mount bazel cache (opcional)
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: bazel

      - name: Clone Copybara versión v20250818
        run: |
          git clone https://github.com/google/copybara.git
          cd copybara
          git checkout v20250818
          bazel build //java/com/google/copybara
      - name: Set Git identity
        run: |
          git config --global user.name "Julimax"
          git config --global user.email "julimax951@gmail.com"
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
      - name: Run Copybara
        run: |
          cd copybara
          ./bazel-bin/java/com/google/copybara/copybara ../copy.bara.sky sync_to_dest --force
