name: Sync with Copybara

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (con el copy.bara.sky)
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # (Opcional pero recomendado) Instalar Bazelisk para obtener la versión correcta de Bazel
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Clone Copybara versión v20250818
        run: |
          git clone https://github.com/google/copybara.git
          cd copybara
          git checkout v20250818

      # ---- Cache de Bazel (repo + disk) y Bazelisk ----
      - name: Prepare Bazel cache dirs
        run: |
          mkdir -p "$HOME/.cache/bazel-repo"
          mkdir -p "$HOME/.cache/bazel-disk"
          mkdir -p "$HOME/.cache/bazelisk"

      - name: Restore Bazel caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel-repo
            ~/.cache/bazel-disk
          key: bazel-${{ runner.os }}-copybara-v20250818-${{ hashFiles('copybara/WORKSPACE*','copybara/MODULE.bazel','copybara/java/**','copybara/third_party/**','copybara/.bazelversion') }}
          restore-keys: |
            bazel-${{ runner.os }}-copybara-v20250818-
            bazel-${{ runner.os }}-

      - name: Build Copybara (usa caches)
        working-directory: copybara
        run: |
          bazel build //java/com/google/copybara \
            --repository_cache="$HOME/.cache/bazel-repo" \
            --disk_cache="$HOME/.cache/bazel-disk"

      - name: Set Git identity
        run: |
          git config --global user.name "Julimax"
          git config --global user.email "julimax951@gmail.com"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: Run Copybara
        working-directory: copybara
        run: |
          ./bazel-bin/java/com/google/copybara/copybara ../copy.bara.sky sync_to_dest --init-history
