name: Validate PR Issue Link

on:
  pull_request:
    types: [opened]  

jobs:
  validate-issue:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  
      issues: read

    steps:
      - name: Check linked issues via GraphQL
        id: check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          # GraphQL: issues that would be closed by merging this PR (via closes/fixes/resolves)
          DATA=$(gh api graphql -f query='
            query($owner:String!, $repo:String!, $pr:Int!){
              repository(owner:$owner, name:$repo){
                pullRequest(number:$pr){
                  closingIssuesReferences(first:20){
                    totalCount
                    nodes { number url title }
                  }
                }
              }
            }' -f owner="$OWNER" -f repo="$REPO" -F pr="$PR_NUMBER")

          COUNT=$(printf '%s' "$DATA" | jq -r '.data.repository.pullRequest.closingIssuesReferences.totalCount')

          if [ "$COUNT" = "0" ] || [ -z "$COUNT" ]; then
            echo "none=true" >> "$GITHUB_OUTPUT"
          else
            echo "none=false" >> "$GITHUB_OUTPUT"
            printf '%s' "$DATA" | jq -r '
              .data.repository.pullRequest.closingIssuesReferences.nodes
              | map("#\(.number) - \(.title) (\(.url))")[]' \
              > issues.txt
            {
              echo "list<<EOF"
              cat issues.txt
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
          fi

      - name: Status — PR has linked issue(s)
        if: steps.check.outputs.none == 'false'
        run: |
          echo "✅ PR has linked issue(s):"
          echo "${{ steps.check.outputs.list }}"

      - name: Status — PR has no linked issues
        if: steps.check.outputs.none == 'true'
        run: |
          echo "⚠️ PR has no linked issues."

      - name: Comment on PR if missing issue link
        if: steps.check.outputs.none == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_FULL: ${{ github.repository }}
        run: |
          gh api repos/$REPO_FULL/issues/$PR_NUMBER/comments \
            -f body=$'⚠️ This Pull Request has no linked issue (via keywords).\n\nPlease add something like **Closes #123** / **Fixes #123** / **Resolves #123** in the PR description to properly link it.'
