name: Validate PR Issue Link

on:
  pull_request:
    types: [opened] 

jobs:
  validate-issue:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  
      issues: read

    steps:
      - name: Scan PR description for Issue URL(s)
        id: scan
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_FULL: ${{ github.repository }}
        run: |
          # Fetch PR body safely (handles null -> empty string)
          BODY=$(gh api repos/$REPO_FULL/pulls/$PR_NUMBER --jq '.body // ""')

          # Look for direct GitHub Issue links (any org/repo)
          URLS=$(printf '%s\n' "$BODY" \
            | grep -Eo 'https://github\.com/[[:alnum:]_.-]+/[[:alnum:]_.-]+/issues/[0-9]+' \
            | sort -u)

          if [ -z "$URLS" ]; then
            echo "none=true" >> "$GITHUB_OUTPUT"
          else
            echo "none=false" >> "$GITHUB_OUTPUT"
            {
              echo "list<<EOF"
              echo "$URLS"
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
          fi

      - name: Status — PR has Issue URL(s)
        if: steps.scan.outputs.none == 'false'
        run: |
          echo "✅ PR description contains Issue URL(s):"
          echo "${{ steps.scan.outputs.list }}"

      - name: Status — PR has no Issue URL
        if: steps.scan.outputs.none == 'true'
        run: |
          echo "⚠️ PR description contains no direct Issue URL."

      - name: Comment on PR if missing Issue URL
        if: steps.scan.outputs.none == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_FULL: ${{ github.repository }}
        run: |
          gh api repos/$REPO_FULL/issues/$PR_NUMBER/comments \
            -f body=$'⚠️ This Pull Request does not include a direct Issue link in its description.\n\nPlease add a URL to a GitHub Issue, for example:\nhttps://github.com/owner/repo/issues/123\n\n(Optional) You can also use keywords like **Closes #123**, but this check only looks for direct links.'
